### ISSUE TITLE
Emotion classification

### ISSUE THREAD

**Issue by diahputri90** [agussuarjaya/Text_Analytic_-Emotion-#1]
if this ML model works, I'm still confused about statement that invite someone as friend, what the emotional classification include?
exsample : 
random tweet "woy rame amat, ga ada yang mau mutualan gitu?" mean "(exclaimed) woy very crowded, no one wants to be mutual?"

**Comment by agussuarjaya** [comment]
You need to retrain the model with more data set if you think that tweet can not be classified to any of those 5 emotions, current ML model only able to classify a tweet into 5.
